# Dependabot configuration file
# Docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Maintain dependencies for npm (Bootstrap project)
  - package-ecosystem: "npm"
    directory: "/bootstrap-v5-sass-portfolio"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Maintain dependencies for npm (Next.js project)
  - package-ecosystem: "npm"
    directory: "/nextjs-tailwind-typescript-portfolio"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
