/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/jsx-no-target-blank */

import React from 'react';
import { Link } from 'gatsby';

import Contact from '../components/Contact';
import Layout from '../components/Layout';

import Footer from '../components/Footer';

const NotFound = () => {
    return (
        <Layout>
            <div className="notFound_home_link">
                <Link to="/">Take me home</Link>
            </div>
            <h1 className="notFound_h1">Privacy Policy</h1>
            <h4 className="notFound_h4">Last updated: December 13, 2020</h4>
            <p className="notFound_p">
                This Privacy Policy describes Our policies and procedures on the collection, use and
                disclosure of Your information when You use the Service and tells You about Your
                privacy rights and how the law protects You.
            </p>
            <p className="notFound_p">
                We use Your Personal data to provide and improve the Service. By using the Service,
                You agree to the collection and use of information in accordance with this Privacy
                Policy.
            </p>
            <h3 className="notFound_h3"> Interpretation and Definitions</h3>
            <p className="notFound_p">
                The words of which the initial letter is capitalized have meanings defined under the
                following conditions. The following definitions shall have the same meaning
                regardless of whether they appear in singular or in plural. For the purposes of this
                Privacy Policy:
            </p>
            <p className="notFound_p">
                <strong>Account</strong>:
            </p>
            <p className="notFound_p">
                A unique account created for You to access our Service or parts of our Service.
            </p>
            <p className="notFound_p">
                <strong>Company:</strong>
            </p>
            <p className="notFound_p">
                (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or
                &quot;Our&quot; in this Agreement) refers to Scott Milliorn.
            </p>
            <p className="notFound_p">
                <strong>Cookies:</strong>
            </p>
            <p className="notFound_p">
                Small files that are placed on Your computer, mobile device or any other device by a
                website, containing the details of Your browsing history on that website among its
                many uses.
            </p>
            <p className="notFound_p">
                <strong>Country</strong>
            </p>
            <p className="notFound_p">United States.</p>
            <p className="notFound_p">
                <strong>Device</strong>
            </p>
            <p className="notFound_p">
                Any device that can access the Service such as a computer, a cellphone or a digital
                tablet.
            </p>
            <p className="notFound_p">
                <strong>Personal Data</strong>
            </p>
            <p className="notFound_p">
                Any information that relates to an identified or identifiable individual.
            </p>
            <p className="notFound_p">
                <strong>Service</strong>
            </p>
            <p className="notFound_p">Refers to the Website.</p>
            <p className="notFound_p">
                <strong>Service Provider</strong>
            </p>
            <p className="notFound_p">
                Any natural or legal person who processes the data on behalf of the Company. It
                refers to third-party companies or individuals employed by the Company to facilitate
                the Service, to provide the Service on behalf of the Company, to perform services
                related to the Service or to assist the Company in analyzing how the Service is
                used.
            </p>
            <p className="notFound_p">
                <strong>Third-party Social Media Service</strong>
            </p>
            <p className="notFound_p">
                Any website or any social network website through which a User can log in or create
                an account to use the Service.
            </p>
            <p className="notFound_p">
                <strong>Usage Data</strong>
            </p>
            <p className="notFound_p">
                refers to data collected automatically, either generated by the use of the Service
                or from the Service infrastructure itself (for example, the duration of a page
                visit).
            </p>
            <p className="notFound_p">
                <strong>Website</strong>
            </p>
            <p className="notFound_p">
                {' '}
                <a
                    href="https://scottmilliorn.netlify.app"
                    rel="external nofollow noopener"
                    target="_blank">
                    https://scottmilliorn.netlify.app
                </a>
            </p>
            <p className="notFound_p">
                <strong>You</strong>
            </p>
            <p className="notFound_p">
                The individual accessing or using the Service, or the company, or other legal entity
                on behalf of which such individual is accessing or using the Service, as applicable.
            </p>
            <br></br>
            <h2 className="notFound_h2">Types of Data Collected</h2>
            <h3 className="notFound_h3"> Personal Data</h3>
            <p className="notFound_p">
                While using Our Service, We may ask You to provide Us with certain personally
                identifiable information that can be used to contact or identify You. Personally
                identifiable information may include, but is not limited to:
            </p>
            <h3 className="notFound_h3"> Usage Data</h3>
            <p className="notFound_p">
                Usage Data is collected automatically when using the Service. However we do not
                store any data on this site.
            </p>
            <p className="notFound_p">
                Usage Data may include information such as Your Device's Internet Protocol address
                (e.g. IP address), browser type, browser version, the pages of our Service that You
                visit, the time and date of Your visit, the time spent on those pages, unique device
                identifiers and other diagnostic data.
            </p>
            <p className="notFound_p">
                When You access the Service by or through a mobile device, We may collect certain
                information automatically, including, but not limited to, the type of mobile device
                You use, Your mobile device unique ID, the IP address of Your mobile device, Your
                mobile operating system, the type of mobile Internet browser You use, unique device
                identifiers and other diagnostic data.
            </p>
            <p className="notFound_p">
                We may also collect information that Your browser sends whenever You visit our
                Service or when You access the Service by or through a mobile device.
            </p>
            <p className="notFound_p">
                We currently do not store or collect any information on the user at this time. Only
                Data that is collected on this site or stored is by Netlify.
            </p>
            <h3 className="notFound_h3"> Tracking Technologies and Cookies</h3>
            <p className="notFound_p">
                We DO NOT use Cookies and similar tracking technologies to track the activity on Our
                Service and store certain information. Tracking technologies used are beacons, tags,
                and scripts to collect and track information and to improve and analyze Our Service.{' '}
            </p>
            <h3 className="notFound_h3"> Use of Your Personal Data</h3>
            <p className="notFound_p">
                The Company may use Personal Data for the following purposes:
            </p>
            <p className="notFound_p">
                <strong>To provide and maintain our Service:</strong>
            </p>
            <p className="notFound_p">including to monitor the usage of our Service.</p>
            <p className="notFound_p">
                <strong>For the performance of a contract:</strong>
            </p>
            <p className="notFound_p">
                the development, compliance and undertaking of the purchase contract for the
                products, items or services You have purchased or of any other contract with Us
                through the Service.
            </p>
            <p className="notFound_p">
                <strong>To contact You:</strong>
            </p>
            <p className="notFound_p">
                by email, telephone calls, SMS, or other equivalent forms of electronic
                communication, such as a mobile application's push notifications regarding updates
                or informative communications related to the functionalities, products or contracted
                services, including the security updates, when necessary or reasonable for their
                implementation.
            </p>
            <p className="notFound_p">
                <strong>To provide You: </strong>
            </p>
            <p className="notFound_p">
                with news, special offers and general information about other goods, services and
                events which we offer that are similar to those that you have already purchased or
                enquired about unless You have opted not to receive such information.
            </p>
            <p className="notFound_p">
                <strong>To manage Your requests:</strong>
            </p>
            <p className="notFound_p">To attend and manage Your requests to Us.</p>
            <p className="notFound_p">
                <strong>For business transfers:</strong>
            </p>
            <p className="notFound_p">
                We may use Your information to evaluate or conduct a merger, divestiture,
                restructuring, reorganization, dissolution, or other sale or transfer of some or all
                of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or
                similar proceeding, in which Personal Data held by Us about our Service users is
                among the assets transferred.
            </p>
            <p className="notFound_p">
                <strong>For other purposes</strong>:
            </p>
            <p className="notFound_p">
                We may use Your information for other purposes, such as data analysis, identifying
                usage trends, determining the effectiveness of our promotional campaigns and to
                evaluate and improve our Service, products, services, marketing and your experience.
            </p>
            <h3 className="notFound_h3">
                We may share Your personal information in the following situations:
            </h3>
            <p className="notFound_p">
                <strong>Service Providers:</strong>
            </p>
            <p className="notFound_p">
                We may share Your personal information with Service Providers to monitor and analyze
                the use of our Service, to contact You.
            </p>
            <p className="notFound_p">
                <strong>For business transfers:</strong>
            </p>
            <p className="notFound_p">
                We may share or transfer Your personal information in connection with, or during
                negotiations of, any merger, sale of Company assets, financing, or acquisition of
                all or a portion of Our business to another company.
            </p>
            <p className="notFound_p">
                <strong>With Affiliates:</strong>
            </p>
            <p className="notFound_p">
                We may share Your information with Our affiliates, in which case we will require
                those affiliates to honor this Privacy Policy. Affiliates include Our parent company
                and any other subsidiaries, joint venture partners or other companies that We
                control or that are under common control with Us.
            </p>
            <p className="notFound_p">
                <strong>With business partners:</strong>
            </p>
            <p className="notFound_p">
                We may share Your information with Our business partners to offer You certain
                products, services or promotions.
            </p>
            <p className="notFound_p">
                <strong>With other users:</strong>
            </p>
            <p className="notFound_p">
                When You share personal information or otherwise interact in the public areas with
                other users, such information may be viewed by all users and may be publicly
                distributed outside. If You interact with other users or register through a
                Third-Party Social Media Service, Your contacts on the Third-Party Social Media
                Service may see Your name, profile, pictures and description of Your activity.
                Similarly, other users will be able to view descriptions of Your activity,
                communicate with You and view Your profile.
            </p>
            <p className="notFound_p">
                <strong>With Your consent</strong>:
            </p>
            <p className="notFound_p">
                We may disclose Your personal information for any other purpose with Your consent.
            </p>
            <h3 className="notFound_h3">Retention of Your Personal Data</h3>
            <p className="notFound_p">
                The Company will retain Your Personal Data only for as long as is necessary for the
                purposes set out in this Privacy Policy. We will retain and use Your Personal Data
                to the extent necessary to comply with our legal obligations (for example, if we are
                required to retain your data to comply with applicable laws), resolve disputes, and
                enforce our legal agreements and policies.
            </p>
            <p className="notFound_p">
                The Company will also retain Usage Data for internal analysis purposes. Usage Data
                is generally retained for a shorter period of time, except when this data is used to
                strengthen the security or to improve the functionality of Our Service, or We are
                legally obligated to retain this data for longer time periods.
            </p>
            <p className="notFound_p">The Company currently retains no personal data.</p>
            <h3 className="notFound_h3"> Transfer of Your Personal Data</h3>
            <p className="notFound_p">
                Your information, including Personal Data, is processed at the Company's operating
                offices and in any other places where the parties involved in the processing are
                located. It means that this information may be transferred to — and maintained on —
                computers located outside of Your state, province, country or other governmental
                jurisdiction where the data protection laws may differ than those from Your
                jurisdiction.
            </p>
            <p className="notFound_p">
                Your consent to this Privacy Policy followed by Your submission of such information
                represents Your agreement to that transfer.
            </p>
            <p className="notFound_p">
                The Company will take all steps reasonably necessary to ensure that Your data is
                treated securely and in accordance with this Privacy Policy and no transfer of Your
                Personal Data will take place to an organization or a country unless there are
                adequate controls in place including the security of Your data and other personal
                information.
            </p>
            <p className="notFound_p">The Company currently retains no personal data.</p>
            <h3 className="notFound_h3"> Disclosure of Your Personal Data</h3>
            <br></br>
            <h3 className="notFound_h3"> Business Transactions</h3>
            <p className="notFound_p">
                If the Company is involved in a merger, acquisition or asset sale, Your Personal
                Data may be transferred. We will provide notice before Your Personal Data is
                transferred and becomes subject to a different Privacy Policy.
            </p>
            <h3 className="notFound_h3"> Law enforcement</h3>
            <p className="notFound_p">
                Under certain circumstances, the Company may be required to disclose Your Personal
                Data if required to do so by law or in response to valid requests by public
                authorities (e.g. a court or a government agency).
            </p>
            <h3 className="notFound_h3"> Other legal requirements</h3>
            <p className="notFound_p">
                <strong>
                    The Company may disclose Your Personal Data in the good faith belief that such
                    action is necessary to:
                </strong>
            </p>

            <p className="notFound_p">Comply with a legal obligation</p>
            <p className="notFound_p">Protect and defend the rights or property of the Company</p>
            <p className="notFound_p">
                Prevent or investigate possible wrongdoing in connection with the Service
            </p>
            <p className="notFound_p">
                Protect the personal safety of Users of the Service or the public
            </p>
            <p className="notFound_p">Protect against legal liability</p>
            <h3 className="notFound_h3"> Security of Your Personal Data</h3>
            <p className="notFound_p">
                The security of Your Personal Data is important to Us, but remember that no method
                of transmission over the Internet, or method of electronic storage is 100% secure.
                While We strive to use commercially acceptable means to protect Your Personal Data,
                We cannot guarantee its absolute security.
            </p>
            <p className="notFound_p">The Company currently retains no personal data.</p>
            <h1 className="notFound_h1">Links to Other Websites</h1>
            <p className="notFound_p">
                Our Service may contain links to other websites that are not operated by Us. If You
                click on a third party link, You will be directed to that third party's site. We
                strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <p className="notFound_p">
                We have no control over and assume no responsibility for the content, privacy
                policies or practices of any third party sites or services.
            </p>
            <p className="notFound_p">The Company currently retains no personal data.</p>
            <h1 className="notFound_h1">Changes to this Privacy Policy</h1>
            <p className="notFound_p">
                We may update Our Privacy Policy from time to time. We will notify You of any
                changes by posting the new Privacy Policy on this page.
            </p>
            <p className="notFound_p">
                We will let You know via email and/or a prominent notice on Our Service, prior to
                the change becoming effective and update the &quot;Last updated&quot; date at the
                top of this Privacy Policy.
            </p>
            <p className="notFound_p">
                You are advised to review this Privacy Policy periodically for any changes. Changes
                to this Privacy Policy are effective when they are posted on this page.
            </p>
            <Contact />
            <Footer />
        </Layout>
    );
};

export default NotFound;
